site_name: WavePro Documentation
copyright: Copyright &copy; 2024 Alphaus Cloud. All rights reserved.

theme:
  name: material
  logo: assets/alphaus.png
  favicon: assets/alphaus.png
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - "WavePro":
      - "index.md"
      - "AWS":
        - "wavepro/aws.md"
        - "wavepro/dashboard.md"
        - "wavepro/repto.md"
        - "wavepro/budget-and-forecast.md"
        - "wavepro/notification.md"
        - "wavepro/repto-1.md"
        - "wavepro/repto-repto.md"
  - "Wave":
      - "ripple/index.md"
      - "ripple/concepts.md"
      - "A primer on TrueUnblended": "ripple/trueunblended.md"
      - "Knowledgebase ↗": "https://help.alphaus.cloud/en/"
  - "Aqua":
      - "aqua/index.md"
      - "aqua/utilization.md"
      - "aqua/risp.md"
      - "aqua/recommendation.md"
      - "aqua/rightsizing.md"
      - "aqua/scheduling.md"

extra:
  alternate:
    - name: English
      link: /wavedocs/
      lang: en
    - name: 日本語
      link: /wavedocs-ja/
      lang: ja

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - footnotes
