site_name: WavePro Documentation
copyright: Copyright &copy; 2024 Alphaus Cloud. All rights reserved.

theme:
  name: material
  logo: assets/alphaus.png
  favicon: assets/alphaus.png
  font:
    text: BIZ UDMincho
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - "WavePro":
      - "index.md"
      - "AWS":
        - "wavepro/aws.md"
        - "wavepro/dashboard.md"
        - "wavepro/repto.md"
        - "wavepro/budget-and-forecast.md"
        - "wavepro/notification.md"
        - "wavepro/repto-1.md"
        - "wavepro/repto-repto.md"
        - "wavepro/reportfilter.md"
        - "wavepro/api.md"
      - "Azure":
        - "wavepro/wave-pro-for-azure.md"
      - "SAML":
        - "wavepro/saml.md"
        - "wavepro/saml-subuser.md"
      - "Settings":
        - "wavepro/settings/password.md"
        - "RBAC":
          - "wavepro/settings/rbac/rbac.md"
          - "wavepro/settings/rbac/about-role.md"
          - "wavepro/settings/rbac/how-to-use.md"
      - "wavepro/csvnonitsuite.md"
      - "wavepro/aqua.md"
  - "Wave":
      - "wave/index.md"
      - "AWS":
        - "wave/aws/index.md"
        - "wave/aws/dashboard.md"
        - "wave/aws/usage-reports.md"
        - "wave/aws/reserved-instances.md"
        - "wave/aws/savings-plans.md"
        - "wave/aws/invoice.md"
        - "wave/aws/budget.md"
        - "wave/aws/fee.md"
        - "wave/aws/tag.md"
        - "wave/aws/reportcsv.md"
      - "Azure":
        - "wave/azure/index.md"
        - "wave/azure/dashboard.md"
        - "wave/azure/reoport.md"
        - "wave/azure/reservedinstance.md"
        - "wave/azure/invoice.md"
      - "GCP":
        - "wave/gcp/index.md"
        - "wave/gcp/dashboard.md"
        - "wave/gcp/report.md"
        - "wave/gcp/invoice.md"
      - "共通項目":
        - "wave/settings.md"
        - "wave/rbac.md"
  - "Aqua":
      - "aqua/index.md"
      - "aqua/utilization.md"
      - "aqua/risp.md"
      - "aqua/recommendation.md"
      - "aqua/rightsizing.md"
      - "aqua/scheduling.md"

extra:
  alternate:
    - name: English
      link: /wavedocs/
      lang: en
    - name: 日本語
      link: /wavedocs-ja/
      lang: ja

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - footnotes
